language: generic

branches:
  only:
  - master

deploy:
  provider: s3
  access_key_id:
    secure: GgECQdYIj2cDjIuswnRGiLWjHoJRSMzVdxEnCv6EhHFCgPbIx9G+t23fKYTFv82cijBR6FCxe+v/U4MR0/24McSBjdSfN9ePlp7YEjOK3GyQb5DbyLa03j+Lplolmy5fmjSjnSuB+kjVFUhl0vY+HDQo+HxpyQQg9v4jaivMCCUn9pDQ6RpIGbHuTray8zyzPe+uYPOEzF8kI4pl5tUkCcK1Y16nm8dTIARB7bsI0EqBSFKHlLQXR1ILMqjJd1OaI6X5vfp092+urbaBm5kRjr6wGFd+wJdql4eUjZkZZg650SsNsRKXst3BG1swzm/GrTa2h/ntOZV35nm2kwlsM3Y9JF1DkiVbVVL6PNohwY8vfCKWJMPUFNLc6QAiuYPKIARnIdNBTEhiDBRLjsDxrbGqEfTuBKok0Wi86nMNcaXAEz4qe1B/nID0/p3srbF+l0wTbvhBGDhaumCYDlZbIGHj9fDsSC7/7KPXZfqcxv+fpxGwsV5DFUPWPTWSY4f3z2T71wjsvn/M3AxBn3scKig1ux4lf6fK3nmY2LrGJyYGmURaEMV/ZnrdiKEnP4LJqVa9z87zOKqMFv1pLyTEHxQW/qV2lDV3bcpmLGfMk6lyM08f1IZESIcdy7eTHi1b+wtSpjRueHS+35dJmTnxhW2uvF8Qi46UHLqq9IjwVCs=
  secret_access_key:
    secure: OZdfEbnNwyyNuUyGcVDdcXvkJOKUt2aht3ibxawsrDrGNnIiU7ZExDaFPI4MU9otARAAE08l0d3oRmZTC3hT9Fj5cyXTYwD+q/4UvkQ8o2lCP9mLeLIBshcS5kfjnHBpXgTYv1njys7mXUHHHMx0vNs6jCEnQzsXxVGYnUgDdGv8GkKWZIcyQLx3FtZdDOIyTdIcrsBMLbZuPK1ZHpTC5v7yYVfq3bP0ztHxSfxta3E+7UTUguu9GEwyjX6M2QvLNc7mrAImYSPPC9aKWj0d5mlkuzs25EeX1dclsVQhZxfBYCmfLPJM+q+3UAU2biPI1bc4NcCSu6l19kr8LnfYCc9B9RT7r+gMStJVx+b/SwEPekFAoa1eKHJekM6rGgT2rezFR34Ny8dHrgeI+EwcxV8wm85rHYQrEFIOY5V7xMH00v2vdJMc7vd9daTQT5e7Rc5EBWFMbLM+/Yrmz5ACzK88EblytxohYNl67b2ZPdAPLmsn5jiSoCUruDIG9jp4UwozntvurJiq+VkVZWts+69YylInyirA1/F5V4l+79PuwK4o1DLoT8ZoZL4laltHJzWrglLxjqb/RQqTUHFqEP9Tic/+bcPLrKa09717Ao39GBtpEuCPjWNmJvzb0n/GjZWZKLYqtAv3khBsxMEnnj5ss6zS0vxAnHQ8B+9LbUo=
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/miler-lite
